import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'HospitalOS - Complete Hospital Management System | EMR, OPD, IPD, Lab & More',
  description: 'HospitalOS is a comprehensive hospital management system with 25+ integrated modules including EMR, OPD, IPD, Emergency Triage, Laboratory, Radiology, Pharmacy, Billing, HR & Payroll, Maternity, and more. Built for African healthcare facilities.',
  keywords: [
    // Core product keywords
    'hospital management system',
    'hospital management software',
    'HMS software',
    'electronic medical records',
    'EMR software',
    'EHR system',
    'electronic health records',
    // Department modules
    'OPD management software',
    'IPD management software',
    'hospital billing software',
    'laboratory information system',
    'LIS software',
    'radiology information system',
    'RIS software',
    'pharmacy management hospital',
    'patient registration system',
    'hospital queue management',
    'triage system software',
    'emergency department software',
    'maternity management system',
    'blood bank management',
    'hospital HR payroll',
    'theatre management software',
    // Geographic targeting - Africa
    'hospital software Africa',
    'hospital software Ghana',
    'hospital software Nigeria',
    'hospital software Kenya',
    'hospital software South Africa',
    'hospital software Tanzania',
    'hospital software Uganda',
    'hospital software Rwanda',
    'hospital software Ethiopia',
    'hospital software Cameroon',
    // Geographic - Middle East
    'hospital software UAE',
    'hospital software Dubai',
    'hospital software Saudi Arabia',
    'hospital software Qatar',
    // Geographic - Asia
    'hospital software India',
    'hospital software Philippines',
    'hospital software Bangladesh',
    // Other keywords
    'clinic management software',
    'healthcare management system',
    'NHIS hospital software',
    'NHIF hospital software',
    'hospital insurance claims',
    'offline hospital software',
    'desktop hospital application',
    // Long-tail keywords
    'best hospital software for small hospitals',
    'affordable hospital management system',
    'hospital software without subscription',
    'one-time payment hospital software',
    'hospital software for developing countries',
    'hospital software with telemedicine',
    'hospital software for clinics',
  ],
  openGraph: {
    title: 'HospitalOS - Complete Hospital Management System',
    description: 'Manage your entire hospital with HospitalOS. 25+ integrated modules for OPD, IPD, Emergency, Lab, Radiology, Pharmacy, Billing, HR, and specialized departments.',
    url: 'https://medsoftwares.com/hospitalos',
    siteName: 'MedSoftwares',
    images: [
      {
        url: '/og.png',
        width: 1200,
        height: 630,
        alt: 'HospitalOS - Hospital Management System',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'HospitalOS - Complete Hospital Management System',
    description: 'Manage your entire hospital with HospitalOS. 25+ integrated modules for all departments.',
    images: ['/og.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: 'https://medsoftwares.com/hospitalos',
  },
};

// JSON-LD Structured Data for HospitalOS
export const hospitalOSJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'HospitalOS',
  applicationCategory: 'BusinessApplication',
  applicationSubCategory: 'Hospital Management Software',
  operatingSystem: 'Windows, macOS, Linux',
  description: 'Complete hospital management system with 25+ integrated modules including EMR, OPD, IPD, Emergency Triage, Laboratory, Radiology, Pharmacy, Billing, HR & Payroll, and specialized departments.',
  offers: {
    '@type': 'Offer',
    price: '799',
    priceCurrency: 'USD',
    description: 'Starting from $799 - Contact for pricing',
    availability: 'https://schema.org/InStock',
  },
  featureList: [
    'OPD Management',
    'IPD Management',
    'Emergency/Triage',
    'Laboratory Information System',
    'Radiology Information System',
    'Pharmacy Integration',
    'Billing & Cashier',
    'HR & Payroll',
    'Maternity Care',
    'Pediatrics',
    'Dental Services',
    'Physiotherapy',
    'Dialysis Center',
    'Blood Bank',
    'Operation Theatre',
    'ICU/CCU',
    'Kitchen Management',
    'Mortuary',
    'Ambulance Fleet',
    'Equipment Maintenance',
    'Patient Registration',
    'Queue Management',
    'Vitals Recording',
    'Consultation Notes',
    'Multi-Language Support',
    'Offline Capability',
    'Role-Based Access',
    'Audit Trail',
    'NHIS/Insurance Claims',
  ],
  screenshot: [
    {
      '@type': 'ImageObject',
      url: 'https://medsoftwares.com/screenshots/hospitalos-dashboard.png',
      caption: 'HospitalOS Dashboard',
    },
    {
      '@type': 'ImageObject',
      url: 'https://medsoftwares.com/screenshots/hospitalos-opd.png',
      caption: 'HospitalOS OPD Queue',
    },
  ],
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.9',
    ratingCount: '85',
    bestRating: '5',
    worstRating: '1',
  },
  author: {
    '@type': 'Organization',
    name: 'MedSoftwares',
    url: 'https://medsoftwares.com',
  },
};
