import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'HospitalOS - Complete Hospital Management System | EMR, OPD, IPD, Lab & More',
  description: 'HospitalOS is a comprehensive hospital management system with 25+ integrated modules including EMR, OPD, IPD, Emergency Triage, Laboratory, Radiology, Pharmacy, Billing, HR & Payroll, Maternity, and more. Built for African healthcare facilities.',
  keywords: [
    'hospital management system',
    'hospital management software',
    'HMS software',
    'electronic medical records',
    'EMR software',
    'EHR system',
    'OPD management',
    'IPD management',
    'hospital billing software',
    'laboratory information system',
    'radiology information system',
    'pharmacy management',
    'patient registration',
    'hospital queue management',
    'triage system',
    'emergency department software',
    'maternity management system',
    'blood bank management',
    'hospital HR payroll',
    'hospital software Africa',
    'hospital software Ghana',
    'hospital software Nigeria',
    'hospital software Kenya',
    'clinic management software',
    'healthcare management system',
    'NHIS hospital software',
    'hospital insurance claims',
    'offline hospital software',
    'desktop hospital application',
  ],
  openGraph: {
    title: 'HospitalOS - Complete Hospital Management System',
    description: 'Manage your entire hospital with HospitalOS. 25+ integrated modules for OPD, IPD, Emergency, Lab, Radiology, Pharmacy, Billing, HR, and specialized departments.',
    url: 'https://medsoftwares.com/hospitalos',
    siteName: 'MedSoftware',
    images: [
      {
        url: '/og/hospitalos.png',
        width: 1200,
        height: 630,
        alt: 'HospitalOS - Hospital Management System Dashboard',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'HospitalOS - Complete Hospital Management System',
    description: 'Manage your entire hospital with HospitalOS. 25+ integrated modules for all departments.',
    images: ['/og/hospitalos.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: 'https://medsoftwares.com/hospitalos',
  },
};

// JSON-LD Structured Data for HospitalOS
export const hospitalOSJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'HospitalOS',
  applicationCategory: 'BusinessApplication',
  applicationSubCategory: 'Hospital Management Software',
  operatingSystem: 'Windows, macOS, Linux',
  description: 'Complete hospital management system with 25+ integrated modules including EMR, OPD, IPD, Emergency Triage, Laboratory, Radiology, Pharmacy, Billing, HR & Payroll, and specialized departments.',
  offers: {
    '@type': 'Offer',
    price: '0',
    priceCurrency: 'USD',
    description: 'Contact for pricing',
  },
  featureList: [
    'OPD Management',
    'IPD Management',
    'Emergency/Triage',
    'Laboratory Information System',
    'Radiology Information System',
    'Pharmacy Integration',
    'Billing & Cashier',
    'HR & Payroll',
    'Maternity Care',
    'Pediatrics',
    'Dental Services',
    'Physiotherapy',
    'Dialysis Center',
    'Blood Bank',
    'Operation Theatre',
    'ICU/CCU',
    'Kitchen Management',
    'Mortuary',
    'Ambulance Fleet',
    'Equipment Maintenance',
    'Patient Registration',
    'Queue Management',
    'Vitals Recording',
    'Consultation Notes',
    'Multi-Language Support',
    'Offline Capability',
    'Role-Based Access',
    'Audit Trail',
    'NHIS/Insurance Claims',
  ],
  screenshot: [
    {
      '@type': 'ImageObject',
      url: 'https://medsoftwares.com/screenshots/hospitalos-dashboard.png',
      caption: 'HospitalOS Dashboard',
    },
    {
      '@type': 'ImageObject',
      url: 'https://medsoftwares.com/screenshots/hospitalos-opd.png',
      caption: 'HospitalOS OPD Queue',
    },
  ],
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.9',
    ratingCount: '85',
    bestRating: '5',
    worstRating: '1',
  },
  author: {
    '@type': 'Organization',
    name: 'MedSoftware',
    url: 'https://medsoftwares.com',
  },
};
